apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop-test
  template:
    metadata:
      labels:
        app: crashloop-test
    spec:
      containers:
        - name: crash
          image: busybox
          command: ["sh", "-c", "echo 'crashing now' && exit 1"]
